import { UpstreamError } from '../../../utils/errors';
import type { IntegrationConfig } from '../integrationService';

export interface JiraConfig {
  domain?: string;
  email?: string;
  apiToken?: string;
}

export interface CreateJiraIssueParams {
  projectKey: string;
  summary: string;
  description?: string;
  issueType?: string;
}

const getConfig = (config: IntegrationConfig): JiraConfig => {
  const domain = (config.domain ?? config.workspaceId ?? config.baseUrl) as string | undefined;
  const email = config.email as string | undefined;
  const apiToken = (config.apiKey ?? config.apiToken) as string | undefined;
  if (!domain || !email || !apiToken) {
    throw new UpstreamError('Jira credentials are incomplete (domain/email/apiToken).');
  }
  return { domain, email, apiToken };
};

export const jiraService = {
  async testConnection(config: IntegrationConfig): Promise<{ ok: boolean; message: string }> {
    try {
      const jira = getConfig(config);
      const response = await fetch(`https://${jira.domain}/rest/api/3/myself`, {
        headers: {
          Authorization: `Basic ${Buffer.from(`${jira.email}:${jira.apiToken}`).toString('base64')}`,
        },
      });
      if (!response.ok) return { ok: false, message: `Jira API returned ${response.status}` };
      return { ok: true, message: 'Connected to Jira' };
    } catch (error) {
      return { ok: false, message: (error as Error).message };
    }
  },

  async createIssue(
    config: IntegrationConfig,
    params: CreateJiraIssueParams
  ): Promise<{ issueKey: string; issueUrl: string }> {
    const jira = getConfig(config);
    const response = await fetch(`https://${jira.domain}/rest/api/3/issue`, {
      method: 'POST',
      headers: {
        Authorization: `Basic ${Buffer.from(`${jira.email}:${jira.apiToken}`).toString('base64')}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        fields: {
          project: { key: params.projectKey },
          summary: params.summary,
          description: params.description ?? '',
          issuetype: { name: params.issueType ?? 'Bug' },
        },
      }),
    });
    if (!response.ok) {
      const text = await response.text().catch(() => '');
      throw new UpstreamError(`Jira failed to create issue (${response.status})`, text.slice(0, 500));
    }
    const issue = (await response.json()) as { key: string; self: string };
    return {
      issueKey: issue.key,
      issueUrl: `${jira.domain}/browse/${issue.key}`.replace(/^https?:\/\//, 'https://'),
    };
  },
  
  async createBugIssue(
    config: IntegrationConfig,
    bug: {
      title: string;
      description?: string;
      severity: string;
      priority: string;
      reproductionSteps?: any;
      expectedBehavior?: string;
      actualBehavior?: string;
      screenshotUrl?: string;
      testRunUrl?: string;
    },
    projectKey: string
  ): Promise<{ issueKey: string; issueUrl: string }> {
    const jira = getConfig(config);
    
    // Format reproduction steps
    let reproSteps = '';
    if (bug.reproductionSteps) {
      if (Array.isArray(bug.reproductionSteps)) {
        reproSteps = bug.reproductionSteps
          .map((step: any, idx: number) => `# ${step.action || step}`)
          .join('\n');
      } else if (typeof bug.reproductionSteps === 'string') {
        reproSteps = bug.reproductionSteps;
      }
    }
    
    // Build Jira description in Atlassian Document Format (ADF)
    const description = {
      type: 'doc',
      version: 1,
      content: [
        {
          type: 'heading',
          attrs: { level: 2 },
          content: [{ type: 'text', text: 'Bug Report (Auto-generated by VeriBot)' }],
        },
        {
          type: 'paragraph',
          content: [
            { type: 'text', text: 'Severity: ', marks: [{ type: 'strong' }] },
            { type: 'text', text: bug.severity },
            { type: 'text', text: '  |  ' },
            { type: 'text', text: 'Priority: ', marks: [{ type: 'strong' }] },
            { type: 'text', text: bug.priority },
          ],
        },
        {
          type: 'heading',
          attrs: { level: 3 },
          content: [{ type: 'text', text: 'Description' }],
        },
        {
          type: 'paragraph',
          content: [{ type: 'text', text: bug.description || 'No description provided' }],
        },
      ],
    };
    
    if (reproSteps) {
      description.content.push(
        {
          type: 'heading',
          attrs: { level: 3 },
          content: [{ type: 'text', text: 'Reproduction Steps' }],
        },
        {
          type: 'paragraph',
          content: [{ type: 'text', text: reproSteps }],
        }
      );
    }
    
    if (bug.expectedBehavior) {
      description.content.push(
        {
          type: 'heading',
          attrs: { level: 3 },
          content: [{ type: 'text', text: 'Expected Behavior' }],
        },
        {
          type: 'paragraph',
          content: [{ type: 'text', text: bug.expectedBehavior }],
        }
      );
    }
    
    if (bug.actualBehavior) {
      description.content.push(
        {
          type: 'heading',
          attrs: { level: 3 },
          content: [{ type: 'text', text: 'Actual Behavior' }],
        },
        {
          type: 'paragraph',
          content: [{ type: 'text', text: bug.actualBehavior }],
        }
      );
    }
    
    // Map severity to Jira priority
    const priorityMap: Record<string, string> = {
      CRITICAL: 'Highest',
      HIGH: 'High',
      MEDIUM: 'Medium',
      LOW: 'Low',
    };
    
    const response = await fetch(`https://${jira.domain}/rest/api/3/issue`, {
      method: 'POST',
      headers: {
        Authorization: `Basic ${Buffer.from(`${jira.email}:${jira.apiToken}`).toString('base64')}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        fields: {
          project: { key: projectKey },
          summary: bug.title,
          description,
          issuetype: { name: 'Bug' },
          priority: { name: priorityMap[bug.severity] || 'Medium' },
          labels: ['veribot', 'automated'],
        },
      }),
    });
    
    if (!response.ok) {
      const text = await response.text().catch(() => '');
      throw new UpstreamError(`Jira failed to create issue (${response.status})`, text.slice(0, 500));
    }
    
    const issue = (await response.json()) as { key: string; self: string };
    return {
      issueKey: issue.key,
      issueUrl: `https://${jira.domain}/browse/${issue.key}`,
    };
  },
  
  async updateIssue(
    config: IntegrationConfig,
    issueKey: string,
    update: {
      status?: string;
      assignee?: string;
      comment?: string;
    }
  ): Promise<void> {
    const jira = getConfig(config);
    
    if (update.comment) {
      await fetch(`https://${jira.domain}/rest/api/3/issue/${issueKey}/comment`, {
        method: 'POST',
        headers: {
          Authorization: `Basic ${Buffer.from(`${jira.email}:${jira.apiToken}`).toString('base64')}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          body: {
            type: 'doc',
            version: 1,
            content: [
              {
                type: 'paragraph',
                content: [{ type: 'text', text: update.comment }],
              },
            ],
          },
        }),
      });
    }
    
    if (update.status || update.assignee) {
      const fields: any = {};
      if (update.assignee) fields.assignee = { accountId: update.assignee };
      
      await fetch(`https://${jira.domain}/rest/api/3/issue/${issueKey}`, {
        method: 'PUT',
        headers: {
          Authorization: `Basic ${Buffer.from(`${jira.email}:${jira.apiToken}`).toString('base64')}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ fields }),
      });
    }
  },
  
  async listProjects(config: IntegrationConfig): Promise<Array<{ key: string; name: string }>> {
    const jira = getConfig(config);
    const response = await fetch(`https://${jira.domain}/rest/api/3/project`, {
      headers: {
        Authorization: `Basic ${Buffer.from(`${jira.email}:${jira.apiToken}`).toString('base64')}`,
      },
    });
    
    if (!response.ok) {
      throw new UpstreamError(`Failed to list Jira projects (${response.status})`);
    }
    
    const projects = (await response.json()) as Array<{ key: string; name: string }>;
    return projects;
  },
};
