import { UpstreamError } from '../../../utils/errors';
import type { IntegrationConfig } from '../integrationService';

interface GithubClientConfig {
  token?: string;
  baseUrl?: string;
}

const getClient = (config: IntegrationConfig): GithubClientConfig => {
  const token = config.accessToken ?? config.token;
  if (!token) {
    throw new UpstreamError('GitHub access token is missing.');
  }
  return { token, baseUrl: config.baseUrl ?? 'https://api.github.com' };
};

export interface CreateIssueParams {
  title: string;
  body?: string;
  labels?: string[];
  repository: string;
}

export const githubService = {
  async testConnection(config: IntegrationConfig): Promise<{ ok: boolean; message: string }> {
    try {
      const client = getClient(config);
      const response = await fetch(`${client.baseUrl}/user`, {
        headers: { Authorization: `token ${client.token}` },
      });
      if (!response.ok) {
        return { ok: false, message: `GitHub API returned ${response.status}` };
      }
      const user = (await response.json()) as { login?: string };
      return { ok: true, message: `Connected as ${user.login ?? 'user'}` };
    } catch (error) {
      return { ok: false, message: (error as Error).message };
    }
  },

  async listRepositories(config: IntegrationConfig) {
    const client = getClient(config);
    const response = await fetch(`${client.baseUrl}/user/repos?per_page=100&sort=updated`, {
      headers: { Authorization: `token ${client.token}` },
    });
    if (!response.ok) {
      throw new UpstreamError(`GitHub API returned ${response.status}`);
    }
    return (await response.json()) as Array<{
      full_name: string;
      name: string;
      html_url: string;
      default_branch: string;
    }>;
  },

  async createIssue(config: IntegrationConfig, params: CreateIssueParams): Promise<{ issueUrl: string }> {
    const client = getClient(config);
    const response = await fetch(`${client.baseUrl}/repos/${params.repository}/issues`, {
      method: 'POST',
      headers: {
        Authorization: `token ${client.token}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        title: params.title,
        body: params.body,
        labels: params.labels,
      }),
    });
    if (!response.ok) {
      const text = await response.text().catch(() => '');
      throw new UpstreamError(`GitHub failed to create issue (${response.status})`, text.slice(0, 500));
    }
    const issue = (await response.json()) as { html_url: string; number: number };
    return { issueUrl: issue.html_url };
  },
  
  async createBugIssue(
    config: IntegrationConfig,
    bug: {
      title: string;
      description?: string;
      severity: string;
      priority: string;
      reproductionSteps?: any;
      expectedBehavior?: string;
      actualBehavior?: string;
      screenshotUrl?: string;
      videoUrl?: string;
      consoleLogs?: string[];
      testRunUrl?: string;
    },
    repository: string
  ): Promise<{ issueUrl: string }> {
    const client = getClient(config);
    
    // Format reproduction steps
    let reproSteps = '';
    if (bug.reproductionSteps) {
      if (Array.isArray(bug.reproductionSteps)) {
        reproSteps = bug.reproductionSteps
          .map((step: any, idx: number) => `${idx + 1}. ${step.action || step}`)
          .join('\n');
      } else if (typeof bug.reproductionSteps === 'string') {
        reproSteps = bug.reproductionSteps;
      }
    }
    
    // Build issue body
    const issueBody = `
## 🐛 Bug Report (Auto-generated by VeriBot)

**Severity:** ${bug.severity}  
**Priority:** ${bug.priority}

### Description
${bug.description || 'No description provided'}

### Reproduction Steps
${reproSteps || 'No reproduction steps provided'}

### Expected Behavior
${bug.expectedBehavior || 'Not specified'}

### Actual Behavior
${bug.actualBehavior || 'Not specified'}

### Evidence
${bug.screenshotUrl ? `- 📸 [Screenshot](${bug.screenshotUrl})` : ''}
${bug.videoUrl ? `- 🎥 [Video Recording](${bug.videoUrl})` : ''}
${bug.testRunUrl ? `- 🧪 [Test Run Results](${bug.testRunUrl})` : ''}

${bug.consoleLogs && bug.consoleLogs.length > 0 ? `
### Console Errors
\`\`\`
${bug.consoleLogs.slice(0, 10).join('\n')}
${bug.consoleLogs.length > 10 ? `\n... and ${bug.consoleLogs.length - 10} more errors` : ''}
\`\`\`
` : ''}

---
*🤖 This issue was automatically created by VeriBot*
    `.trim();
    
    // Create labels based on severity
    const labels = ['bug', 'veribot'];
    if (bug.severity === 'CRITICAL') labels.push('critical', 'priority-high');
    else if (bug.severity === 'HIGH') labels.push('priority-high');
    else if (bug.severity === 'MEDIUM') labels.push('priority-medium');
    else labels.push('priority-low');
    
    return this.createIssue(config, {
      title: `🐛 ${bug.title}`,
      body: issueBody,
      labels,
      repository,
    });
  },
  
  async updateIssue(
    config: IntegrationConfig,
    repository: string,
    issueNumber: number,
    update: { state?: 'open' | 'closed'; labels?: string[]; body?: string }
  ): Promise<void> {
    const client = getClient(config);
    const response = await fetch(`${client.baseUrl}/repos/${repository}/issues/${issueNumber}`, {
      method: 'PATCH',
      headers: {
        Authorization: `token ${client.token}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(update),
    });
    
    if (!response.ok) {
      throw new UpstreamError(`GitHub failed to update issue (${response.status})`);
    }
  },
  
  async createPullRequest(
    config: IntegrationConfig,
    repository: string,
    params: {
      title: string;
      body: string;
      head: string; // branch name
      base: string; // target branch (usually 'main' or 'master')
    }
  ): Promise<{ prUrl: string }> {
    const client = getClient(config);
    const response = await fetch(`${client.baseUrl}/repos/${repository}/pulls`, {
      method: 'POST',
      headers: {
        Authorization: `token ${client.token}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(params),
    });
    
    if (!response.ok) {
      const text = await response.text().catch(() => '');
      throw new UpstreamError(`GitHub failed to create PR (${response.status})`, text.slice(0, 500));
    }
    
    const pr = (await response.json()) as { html_url: string };
    return { prUrl: pr.html_url };
  },
  
  async addComment(
    config: IntegrationConfig,
    repository: string,
    issueNumber: number,
    comment: string
  ): Promise<void> {
    const client = getClient(config);
    const response = await fetch(`${client.baseUrl}/repos/${repository}/issues/${issueNumber}/comments`, {
      method: 'POST',
      headers: {
        Authorization: `token ${client.token}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ body: comment }),
    });
    
    if (!response.ok) {
      throw new UpstreamError(`GitHub failed to add comment (${response.status})`);
    }
  },
};
